### ISSUE TITLE
Confirmation that C-ICAP can handle traffic through a TLS connection

### ISSUE THREAD

**Issue by tstepany** [k8-proxy/p1-stakeholder-requests#7]
We have a requirement to support TLS v1.2 or higher on all connections into the Glaswall ICAP System. This includes the ICAP Server port. The ICAP Server port management and is provided by the C-ICAP code base, which is an open-source project that Glasswall do not have full experience or knowledge of. From the C-ICAP server configuration file it appears that the server can be configured to provide a port that receives connections through TLS. We need to know that this is true, and to understand how to setup the C-ICAP Server to receive traffic through a connection that uses TLS encryption.

 Output: 
1. Confirmation that C-ICAP can handle traffic through a TLS connection, please as soon as you make it configured and you are sure that it can be handled, provide that confirmation ASAP before moving to step 2. 

2. Detailed step by step instructions on how to configure the C-ICAP to open a port that receives ICAP messages through a TLS encrypted connection. Having video to show how it works will be also great .

**Comment by NourEddineX** [comment]
@tstepany 
After doing a quick research I can confirm that [C-ICAP supports TLS up to v1.2](http://c-icap.sourceforge.net/c-icap.conf-0.5.x.html#tag_TlsPort) 
I'll go ahead for **2.**

**Comment by azopat** [comment]
I can confirm that it works. This is output from the install i just did. and the result from the test client :  
root@yamo-dev /usr/local/c-icap/cert # /usr/local/c-icap/bin/c-icap-client -i localhost -p 1345 -tls -tls-no-verify -tls-method TLSv1_2
Peer cert verification failed: self signed certificate
ICAP server:localhost, ip:127.0.0.1, port:1345

OPTIONS:
	Allow 204: Yes
	Preview: 1024
	Keep alive: Yes

ICAP HEADERS:
	ICAP/1.0 200 OK
	Methods: RESPMOD, REQMOD
	Service: C-ICAP/0.5.6 server - Echo demo service
	ISTag: CI0001-XXXXXXXXX
	Transfer-Preview: *
	Options-TTL: 3600
	Date: Fri, 02 Oct 2020 15:02:58 GMT
	Preview: 1024
	Allow: 204
	X-Include: X-Authenticated-User, X-Authenticated-Groups
	Encapsulated: null-body=0

**Comment by azopat** [comment]
In order to achieve that, the following should be done :  
- Very important : Install ssl libs on the server , otherwise ssl support wont be added to icap : apt-get install libssl-dev

- Setup icap server using normal installation process. 

- Generate ssl key pair (for testing you can generate a self signed key)
openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem

- Edit icap server config and add this line for tls support
TlsPort 1345 tls-method=TLSv1_2 cert=/path/to/cert/certificate.pem key=/path/to/cert/key.pem

- Start the icap server
/usr/local/c-icap/bin/c-icap -N -D -d 10

**Comment by GINAGC** [comment]
Adding instructions from PR here:

**Requirements**
OS: Ubuntu LTS
libssl 1.1
OpenSSL

**Install SSL dependencies**
sudo apt-get install libssl-dev libssl1.1 openssl

**Install C-ICAP from source code**
Download the c-icap source and change to the icap source directory, and run the commands bellow

```
tar xvf c_icap-0.5.6.tar.gz
cd c_icap-0.5.6/
./configure --prefix=/usr/local/c-icap
make
sudo make install
```

**Generate a self signed cert (for testing)**
```
cd /usr/local/c-icap && mkdir cert && cd cert
openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
sudo chown -R c-icap:c-icap /usr/local/c-icap/cert
```
You will need to fill up certificate parameters.

**ICAP configuration**
Edit the c-icap.conf file using sudo nano /usr/local/c-icap/c-icap.conf
TlsPort 1345 tls-method=TLSv1_2 cert=/usr/local/c-icap/cert/certificate.pem key=/usr/local/c-icap/cert/key.pem

**Start icap server**
sudo /usr/local/c-icap/bin/c-icap -N -D -d 10

**Test ICAP server for TLS support**
sudo /usr/local/c-icap/bin/c-icap-client -i localhost -p 1345 -tls -tls-no-verify -tls-method TLSv1_2


**Privileges management
Get pods running with elevated privileges.**
The command below will list all pods running with elevated privileges on the cluster.

`kubectl get pods -o=jsonpath='{range .items[?(@.spec.containers[*].securityContext.privileged==true)]}{.metadata.name}{"\n"}{end}' --all-namespaces`

**Check if glasswall container runs as root**
The check above only make sure the container doesn't run as a priviledged container, but it can still run as root if the docker image is configured with the root user. To check that run the command

`kubectl -n <glasswall_namespace_name> exec -it <glasswall_pod_name> -- bash -c "id -u"`

Make sure the returned user ID is not zero (root)

**Best Practices**
- It's necessary to have a good mechanism to enforce and block pods trying to run with elevated privileges (for instance images configured with root user).
- To achieve that, we need to enable when installing the cluster the PodSecurityPolicy admission controller.
- Admission controllers in kubernetes is a mecanism to add some addtionnal validation on k8s ressources before they are admitted to the cluster. PodSecurityPolicy Admission controller will act on the creation or modification of pods in order to determine if they should be admitted based on the policy defined by the administrator.
- Once that admission controller is enabled, we can setup a default Pod Security Policy that will be inforced to all pods.


```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
```

With that, we are preventing any pod trying to run as root to be scheduled as well as any privileged pod.

Dockerfile should therefore be configured to not use the root as the default user. As presented below :

```
FROM nginx:latest
USER 1001
CMD ["nginx","-g","daemon off;"]
```

The cluster admin can still configure other security policies with more privileges which can be granted to a service account in case of a real need for privilege escalation.
